int alu(int opcode, int operand0, int operand1, int immediate_operand) {
	if (opcode == 0) {
		return operand0;
	}
    if (opcode == 1) {
        return immediate_operand;
    }
	if (opcode == 2) {
		return operand0 + operand1;
	}
    if (opcode == 3) {
        return operand0 + immediate_operand;
    }
	if (opcode == 4) {
		return operand1 - operand0;
	}
    if (opcode == 5) {
        return operand0 - immediate_operand;
    }
    if (opcode == 6) {
        return immediate_operand - operand0;
    }
    /*
    if (opcode == 7) {
        // max(operand0, operand1)
        return operand0 > operand1 ? operand0 : operand1;
    }
    if (opcode == 8) {
        // max(operand0, immediate_operand)
        return operand0 > immediate_operand ? operand0 : immediate_operand;
    }
    if (opcode == 9) {
        // min(operand0, operand1)
        return operand0 > operand1 ? operand1 : operand0;
    }
    else {
        // min(operand0, immediate_operand)
        return operand0 > immediate_operand ? immediate_operand : operand0;
    }*/
}

generator int expr(fun vars, int bnd) {
	assert bnd >= 1;
    int t = ??(1);

    if (t == 0) {
        return alu(??, vars(), vars(), ??);
    }
    if (t == 1) {
        return alu(??, expr(vars, bnd-1), expr(vars, bnd-1), ??);
    }
}

int comp_1(int p_drop0, int p_src0, int p_established_p_array_index1_2, int p_dst0){
	int p_drop2;
	int p_drop1;
	bit p_br_tmp2;
	p_br_tmp2 = !(p_src0 == 102) && (p_dst0 == 102);
	p_drop1 = ( p_established_p_array_index1_2 == 0 );
	p_drop2 = p_br_tmp2 ? p_drop1 : p_drop0;
	return p_br_tmp2;
}

harness void sketch(int p_drop0, int p_src0, int p_established_p_array_index1_2, int p_dst0) {
	generator int vars(){
		return {| 1 | p_drop0 | p_src0 | p_established_p_array_index1_2 | p_dst0 |};
	}
